# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Enterprise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 #use_frameworks!

  # Pods for Enterprise

pod "TPKeyboardAvoidingSwift", '~> 3.1' 
pod 'SVProgressHUD', '~> 2.2.5' 
pod 'GoogleMaps', '~> 2.7.0' 
pod 'GooglePlaces', '~> 2.7.0'
pod 'MagicalRecord', '~> 2.3.2'
pod 'Cosmos', '~> 17.0'
pod 'IQKeyboardManagerSwift', '~> 6.2.0'
pod 'SkyFloatingLabelTextField', '~> 3.6.0'

  target 'EnterpriseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnterpriseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
